language: node_js

node_js: 
  - "10"

before_script:
  - pyenv versions
  - pyenv global 3.6.3
  - python --version
  - pip3 install -r requirements.txt --user
  - npm run build

after_success:
  - if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ]; then
        npm run pre-deploy-test;
        pip3 install -r requirements.txt --user;
        npm run deploy;
      fi

notifications:
  email: false
