dist: xenial
language: node_js

node_js: 
  - "10"

before_script:
  - pyenv global 3.7
  - python --version
  - pip3 install -r requirements.txt --user

script:
  - npm run build
  - npm t
  - if [ $TRAVIS_PULL_REQUEST == true ] && [ $TRAVIS_BRANCH != "master" ]; then
      npm run tag;
    fi

before_deploy:
  # - npm run pre-deploy-test
  - export VERSION=${TRAVIS_TAG:-$(npm run echo-version --silent)}
  - if [ -z "$TRAVIS_TAG" ]; then npm run tag; fi
  - npm run zip

deploy:
  - provider: releases
    api_key:
      secure: ZasTUEzstxWZpCWs/ZL5iI3tjPr0mdlsyWTeS5XsLLyIxVw499q7CgQWDPkj88jXbzonw+6jsQCnQSdoYfbEucgMAE/PHeoggczPvKNTBdG8cWZuqY8BWznCuTDHptu21aqLalgtpYlB8ri5kUvCFAqF64z/sYVG3Iw9sPKaPeGu0NFqXB8Zp4nrBAxDrj5wDVFieRkysA6+r6H7Lu/Oy7cavqTWe12qP7BSUG32QlgW6QTQNXCpvJ5Go8/Iv9D4BXZSk5aNTTaAdq7iN5j/Kdp5ydKmbYVppAr2oEbTfmct63z0AiuPp8RzrLhlCqNxgteCSCUI+UytgHBtzyCCPjRGFpHBhXFcUwzBICopXmHiLs2vCuQ8gnu/t/7v3/9ymseuo0N/MvWoca35HFDGWAYbW5T8fkVHaCWzL1R3dzmuCWokppJ/G1eyJ76uMcjkX88gnBY4iuu3BzsVw8G3BeL4+dREbFViDDEaknllNXK4mDSiaJkwHj10liij/NtCR3w/hg50vvt01aRFplZHgxXcx7rsVRIhn78/NQi6TJEzhTZRc7ZH2LNsjQfNAp+M84vW9SiRMaMMj5biYCernhZxqcTRC/1zmxv20p6hZEhKFZ3dpuo7eCcX/Kj2VGmeiXf/89xfQBLXRc7r38/Z7TqOajeyAZR1aMqmstqvfvw=
    file: $VERSION.zip
    skip_cleanup: true
    on:
      branch: master
      condition: type != pull_request
  - provider: script
    skip_cleanup: true
    script: npm run deploy
    on:
      tags: true

notifications:
  email: false
